core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('application/', views.application, name='application')
    
    
]

dashboard/urls.py
from django.urls import path
from dashboard import views

app_name = "dashboard"

urlpatterns =[
    path("", views.dashboard, name="dashboard"),
    path("profile/", views.teacherprofile, name="profile"),
    path("admissions/", views.admissions, name="admissions"),
    path("add_result/", views.add_result, name="add_results"),
    path("results/", views.results, name="results"),
    path('edit-product/<pk>', views.edit_result, name='edit_result'),
    path('delete/<pk>', views.delete_result, name='delete_result'),
    
    
    
    ######### student url ########
    
    path("student", views.student_dashboard, name="stu_dashboard"),
    path("fees/", views.pay_fees, name="pay_fees"),
    path('pay/review/', views.review_payment, name='review_payment'),
    path('pay/flutterwave/', views.process_flutterwave_payment, name='process_flutterwave_payment'),
    path('payment/callback/', views.flutterwave_callback, name='flutterwave_callback'),
    path('check-results/', views.check_result, name='check_result'),
    path('my-result/<int:session_id>/<int:semester_id>/', views.my_result, name='result_page'),
    path('hostel/', views.Hostel, name='hostel'),
    path('pay/review/', views.rev_hostelpay, name='review_hostel'),
    

    

    
    
    
    
    
]

marizu_uni/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path("user/", include("userauths.urls")),
    path("dashboard/", include("dashboard.urls")),
    
    
]


if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.Registerview, name="sign-up"),
    path("sign-in/", views.Loginview, name="sign-in"),
    path("logout/", views.logoutView, name="logout"),

    
]

templates/include/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Dashboard - tobe</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'asset/img/Group 1.png' %}" rel="icon">
  <link href="{% static 'asset/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'asset/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'asset/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'asset/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'asset/vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'asset/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'asset/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'asset/vendor/simple-datatables/style.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>



  <!-- Template Main CSS File -->
  <link href="{% static 'asset/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin - v2.4.1
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">
    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url 'dashboard:dashboard'%}" class="logo d-flex align-items-center">
        <!-- <img src="{% static 'asset/img/fred-logo.png' %}" alt="" /> -->
      </a>
    </div>
    <!-- End Logo -->
    <i class="bi bi-list toggle-sidebar-btn"></i>

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">
         
            
          
        <li class="nav-item dropdown pe-3">
          <a
            class="nav-link nav-profile d-flex align-items-center pe-0"
            href="{% url 'dashboard:profile' %}"
            data-bs-toggle="dropdown"
          >
            <img
              src="{% static 'asset/img/profile-img.jpg' %}"
              alt="Profile"
              class="rounded-circle"
            />
            <span class="d-none d-md-block ps-2"
              >{{request.user.username}}</span
            > </a
          ><!-- End Profile Iamge Icon -->

          
          <!-- End Profile Dropdown Items -->
        </li>
        <!-- End Profile Nav -->
      </ul>
    </nav>
    <!-- End Icons Navigation -->
  </header>

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">
    <ul class="sidebar-nav" id="sidebar-nav">
      {% if request.user_type == 'teacher'%}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:dashboard'%}">
          <i class="bi bi-grid-fill"></i>
          <span>Overview</span>
        </a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'dashboard:stu_dashboard'%}">
          <i class="bi bi-grid-fill"></i>
          <span>Overview</span>
        </a>
      </li>
      {% endif %}
      <!-- End Dashboard Nav -->
      {% if request.user.user_type == 'teacher'%}
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'dashboard:admissions'%}">
          <i class="bi bi-calendar-week"></i>
          <span>Admissions</span>
        </a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'dashboard:pay_fees'%}">
          <i class="bi bi-calendar-week"></i>
          <span>Pay fees</span>
        </a>
      </li>
      {% endif %}
      <!-- End Attendance Page Nav -->
    {% if request.user.user_type == 'teacher'%}
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'dashboard:results' %}">
          <i class="bi bi-mortarboard-fill"></i>
          <span>Results</span>
        </a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'dashboard:check_result' %}">
          <i class="bi bi-book"></i>
          <span>Check Results</span>
        </a>
      </li>
      {% endif %}

      {% if request.user.user_type == 'student' %}
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'dashboard:hostel' %}">
          <i class="bi bi-bank"></i>
          <span>Hostel</span>
        </a>
      </li>
      {% endif %}
      <!-- End Lecturers Page Nav -->

      <li class="nav-item">
      <a class="nav-link collapsed" href="{% url 'dashboard:profile' %}">
          <i class="bi bi-person"></i>
          <span>Profile</span>
        </a>
      </li>
      <!-- End Department Page Nav -->

      <li class="nav-items">
        <a class="nav-links collapsed" href="{% url 'userauths:logout' %}">
          <i class="bi bi-box-arrow-right"></i>
          <span>logout</span>
        </a>
      </li>
      <!-- End Profile Page Nav -->
    </ul>
  </aside>

  {% block content %}
  {% endblock content %}


  <!-- ======= Footer ======= -->
 {% if messages %}
  <script>
    {% for message in messages %}
      Swal.fire({
        icon: '{% if message.tags == "success" %}success{% else %}error{% endif %}',
        title: '{{ message.tags|capfirst }}',
        text: '{{ message }}',
        confirmButtonColor: '#3085d6'
      });
    {% endfor %}
  </script>
{% endif %}

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'asset/vendor/apexcharts/apexcharts.min.js' %}"></script>
  <script src="{% static 'asset/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'asset/vendor/chart.js/chart.min.js' %}"></script>
  <script src="{% static 'asset/vendor/echarts/echarts.min.js' %}"></script>
  <script src="{% static 'asset/vendor/quill/quill.min.js' %}"></script>
  <script src="{% static 'asset/vendor/simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'asset/vendor/tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'asset/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'asset/js/main.js' %}"></script>

</body>

</html>